### ISSUE TITLE
update build to Qt 5.12.5 or later after alpha release

### ISSUE THREAD

**Issue by kevinhendricks** [kevinhendricks/BuildSigilOnMac#1]
Remember to update this build to Qt 5.12.5 or later after alpha release of Sigil-1.0.

**Comment by kevinhendricks** [comment]
[cmark-gfm.zip](https://github.com/kevinhendricks/BuildSigilOnMac/files/3815857/cmark-gfm.zip)

**Comment by kevinhendricks** [comment]
macOS build of cmark-gfm, statically linked and set for MACOSX_DEPLOYMENT_TARGET=10.12 to match Sigil's current build.

**Comment by kevinhendricks** [comment]
A modified version of Markdown_v0.1.1.zip to work with non-standard epubs.
[MarkdownImport_v0.1.2.zip](https://github.com/kevinhendricks/BuildSigilOnMac/files/3827762/MarkdownImport_v0.1.2.zip)

**Comment by dougmassay** [comment]
If you have to update this for the newer version of PyQt5 to work with Qt5.12.6, this might be a good time to create a release and add the xz tar archive as a binary that can then be updated. I can update the travis.yml easily to accommodate such a change. Your call. It's no harder to pull it from the tree for the automated builds.

I'm probably going to update all the extra Python modules to the latest versions while I'm at it for the Windows builds (but I want to give Pillow 6.2.1 a pretty good testing first).

**Comment by kevinhendricks** [comment]
Will do.  I will delete the binary xz, that I check in and will update the patches and build instructions and then add a pre-built python-3.7.2.txz and qt-5.12.6.xz binaries to the releases page.

What specific versions of Pillow, lxml, etc will you be using for Windows?  I will sync the macOS python modules to match before uploading.

**Comment by dougmassay** [comment]
Sounds good.

With the exception of PyQt5 and Sip, I was planning on updating to the latest versions of the modules. Pillow's the only one I'm really concerned with. Its development has been moving pretty quickly since I last updated it. So I want to make sure there's no problems moving from version 5.x.x to version 6.x.x.

I'll get you the list of version numbers for each one tomorrow morning sometime.

**Comment by kevinhendricks** [comment]
Okay, made these changes and pushed them.   Besides the python module updates and Qt version updates,  the biggest changes are:

1. these binaries now come from releases
2. Qt512.tar.xz ==> Qt5126.tar.xz and unpacks into ~/Qt5126/

**Comment by kevinhendricks** [comment]
This now works for travis ci for both Sigil master and PageEdit master.  So closing this issue as fixed.
